services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/wding/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/wding/data/wordpress
      o: bind
